language: java

jdk:
- oraclejdk8
- oraclejdk9
- oraclejdk10
- openjdk8
- openjdk9
- openjdk10

jobs:
  include:
  - stage: install
    script: mav clean install

branches:
  only:
  - master
  - soap-dev