
/*
 * Copyright (c) 2018 Sergei Visotsky
 *
 */

package org.sergei.soap.ws.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sergei.soap.CustomerDTO;
import org.sergei.soap.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Customer", targetNamespace = "http://soap.sergei.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Customer {


    /**
     * 
     * @param inputCustomerId
     */
    @WebMethod(action = "deleteCustomerById")
    @RequestWrapper(localName = "deleteCustomer", targetNamespace = "http://soap.sergei.org", className = "DeleteCustomer")
    @ResponseWrapper(localName = "deleteCustomerResponse", targetNamespace = "http://soap.sergei.org", className = "DeleteCustomerResponse")
    @Action(input = "deleteCustomerById", output = "http://soap.sergei.org/Customer/deleteCustomerResponse")
    public void deleteCustomer(
        @WebParam(name = "inputCustomerId", targetNamespace = "")
        Long inputCustomerId);

    /**
     * 
     * @return
     *     returns java.util.List<CustomerDTO>
     */
    @WebMethod(action = "getAllCustomers")
    @WebResult(name = "outputAllCustomers", targetNamespace = "")
    @RequestWrapper(localName = "getAllCustomers", targetNamespace = "http://soap.sergei.org", className = "GetAllCustomers")
    @ResponseWrapper(localName = "getAllCustomersResponse", targetNamespace = "http://soap.sergei.org", className = "GetAllCustomersResponse")
    @Action(input = "getAllCustomers", output = "http://soap.sergei.org/Customer/getAllCustomersResponse")
    public List<CustomerDTO> getAllCustomers();

    /**
     * 
     * @param inputCustomerId
     * @return
     *     returns CustomerDTO
     */
    @WebMethod(action = "getCustomerById")
    @WebResult(name = "outputCustomer", targetNamespace = "")
    @RequestWrapper(localName = "getCustomerById", targetNamespace = "http://soap.sergei.org", className = "GetCustomerById")
    @ResponseWrapper(localName = "getCustomerByIdResponse", targetNamespace = "http://soap.sergei.org", className = "GetCustomerByIdResponse")
    @Action(input = "getCustomerById", output = "http://soap.sergei.org/Customer/getCustomerByIdResponse")
    public CustomerDTO getCustomerById(
        @WebParam(name = "inputCustomerId", targetNamespace = "")
        Long inputCustomerId);

    /**
     * 
     * @param firstName
     * @param lastName
     * @param age
     */
    @WebMethod(action = "addCustomer")
    @RequestWrapper(localName = "saveCustomer", targetNamespace = "http://soap.sergei.org", className = "SaveCustomer")
    @ResponseWrapper(localName = "saveCustomerResponse", targetNamespace = "http://soap.sergei.org", className = "SaveCustomerResponse")
    @Action(input = "addCustomer", output = "http://soap.sergei.org/Customer/saveCustomerResponse")
    public void saveCustomer(
        @WebParam(name = "firstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "lastName", targetNamespace = "")
        String lastName,
        @WebParam(name = "age", targetNamespace = "")
        Integer age);

}
